version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: location_sharing_postgres
    environment:
      POSTGRES_DB: location_sharing
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend_elixir/priv/repo/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d location_sharing"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - location_sharing_network

  # pgAdmin (PostgreSQL GUI) - Optional
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: location_sharing_pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - location_sharing_network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  location_sharing_network:
    driver: bridge