global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"
  - "recording-rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Rust API Server
  - job_name: 'rust-api'
    static_configs:
      - targets: ['rust-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Rust WebSocket Server  
  - job_name: 'rust-websocket'
    static_configs:
      - targets: ['rust-ws:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Elixir Backend
  - job_name: 'elixir'
    static_configs:
      - targets: ['elixir:4000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 5s

  # PostgreSQL (if we add postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093